# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: atrick - working swift docs
email: atrick@apple.com
description: > # > means to ignore newlines until the next unindented line
timezone: America/Los_Angeles
baseurl: ""
url: "http://atrick.github.io"

exclude: [config.ru, Gemfile, Gemfile.lock, Procfile, vendor, README.md]

# twitter_username: atrick
# github_username:  atrick

# Build settings
markdown: kramdown

kramdown:
    syntax_highlighter: rouge

sass:
    style: compressed
    sass_dir: _sass

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      official_site: http://atrick.github.io
      official_url: ""
      include_in_navigation: true
